import {ThemeProvider} from "@/components/theme-provider";

import Header from "@/components/screenComponents/Header";
import {Toaster} from "@/components/ui/toaster";
import type {Metadata} from "next";
import {Space_Grotesk} from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./lib/ReactQueryProvider";

const space_grostek = Space_Grotesk({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Split App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_grostek.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Header />
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
